
-- USUARIO ADMIN

-- CASO 1: ESTRATEGIA DE SEGURIDAD 

-- CREAR USUARIOS --

---- USUARIO OWNER
CREATE USER PRY2205_EFT 
IDENTIFIED BY UsuarioBD.2025! 
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

---- USUARIO DES
CREATE USER PRY2205_EFT_DES 
IDENTIFIED BY Usuario2.25!  
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

---- USUARIO CON
CREATE USER PRY2205_EFT_CON 
IDENTIFIED BY Usuario3.2025!  
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

-- CREACIÓN DE ROLES --
CREATE ROLE PRY2205_ROL_D; -- ROL D
CREATE ROLE PRY2205_ROL_C; -- ROL C

-- ASIGNACIÓN DE ROLES --
GRANT PRY2205_ROL_D TO PRY2205_EFT_DES; 
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON; 


-- ASIGNACIÓN DE PRIVILEGIOS --

---- ASIGNACIÓN DE PRIVILEGIOS USUARIO OWNER
GRANT CREATE SESSION TO PRY2205_EFT;

GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE SYNONYM,
CREATE PUBLIC SYNONYM TO PRY2205_EFT;

---- ASIGNACIÓN DE PRIVILEGIOS USUARIO DES
GRANT CREATE SESSION TO PRY2205_ROL_D;

GRANT CREATE VIEW, CREATE PROFILE, 
CREATE USER TO PRY2205_ROL_D;

---- AISGNACIÓN DE PRIVILEGIOS USUARIO CON
GRANT CREATE SESSION TO PRY2205_ROL_C; 


-- USUARIO PRY2205_EFT

-- CASO 2

-- CREACIÓN DE SINÓNIMOS PARA SER USADOS POR USUARIO DES
CREATE SYNONYM SYN_TRABAJADOR FOR PRY2205_EFT.PROFESIONAL;
CREATE SYNONYM SYN_PROF       FOR PRY2205_EFT.PROFESION;
CREATE SYNONYM SYN_PREVISON   FOR PRY2205_EFT.ISAPRE;
CREATE SYNONYM SYN_CONT       FOR PRY2205_EFT.TIPO_CONTRATO;
CREATE SYNONYM SYN_PAGO       FOR PRY2205_EFT.RANGOS_SUELDOS;

-- OTORGAR PRIVILEGIOS A USUARIO DES SOBRE SUS OBJETOS
GRANT SELECT ON PRY2205_EFT.PROFESIONAL TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.PROFESION TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.ISAPRE TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.TIPO_CONTRATO TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.RANGOS_SUELDOS TO PRY2205_ROL_D;
GRANT INSERT, SELECT ON PRY2205_EFT.CARTOLA_PROFESIONALES 
TO PRY2205_ROL_D; -- INSERTAR DATOS EN CARTOLA
GRANT SELECT ON CARTOLA_PROFESIONALES TO PRY2205_EFT_DES
WITH GRANT OPTION; -- HABILITAR A USUARIO DES PARA ORTORGAR PERMISO A USUARIO CON

-- CASO 3

-- CASO 3.1

SHOW USER;

-- CREACIÓN DE SINÓNIMOS PARA SER USADOS POR USUARIO
CREATE SYNONYM SYN_EMPRESA  FOR PRY2205_EFT.EMPRESA;
CREATE SYNONYM SYN_ASESORIA FOR PRY2205_EFT.ASESORIA;

-- OTORGAR PRIVILEGIOS A USUARIO CON 
GRANT SELECT ON VW_EMPRESAS_ASESORADAS TO PRY2205_ROL_C;

-- CREACIÓN DE VISTA
CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT
  TO_CHAR(empresa.RUT_EMPRESA, 'FM9G999G999G999')
  || '-' ||
  empresa.DV_EMPRESA AS RUT_EMPRESA,
  empresa.NOMEMPRESA AS NOMBRE_EMPRESA,
  empresa.IVA_DECLARADO AS IVA,
  TRUNC(
      MONTHS_BETWEEN(
          SYSDATE,
          empresa.FECHA_INICIACION_ACTIVIDADES
      ) / 12
  ) AS ANIOS_EXISTENCIA, 
  TRUNC(COUNT(*) / 12) AS TOTAL_ASESORIAS_ANUALES,
  ROUND(empresa.IVA_DECLARADO * TRUNC(COUNT(*) / 12) / 100,0) AS DEVOLUCION_IVA,
  
  CASE
    WHEN TRUNC(COUNT(*) / 12) > 5 THEN 'CLIENTE PREMIUM'
    WHEN TRUNC(COUNT(*) / 12) BETWEEN 3 AND 5 THEN 'CLIENTE'
    ELSE 'CLIENTE POCO CONCURRIDO'
  END AS TIPO_CLIENTE,

  CASE
    WHEN TRUNC(COUNT(*) / 12) > 5 AND COUNT(*) >= 7
         THEN '1 ASESORIA GRATIS'

    WHEN TRUNC(COUNT(*) / 12) > 5 AND COUNT(*) < 7
         THEN '1 ASESORIA 40% DESCUENTO'

    WHEN TRUNC(COUNT(*) / 12) BETWEEN 3 AND 5 AND COUNT(*) = 5
         THEN '1 ASESORIA 30% DESCUENTO'

    WHEN TRUNC(COUNT(*) / 12) BETWEEN 3 AND 5 AND COUNT(*) < 5
         THEN '1 ASESORIA 20% DESCUENTO'
    ELSE 'CAPTAR CLIENTE'
  END AS CORRESPONDE
FROM SYN_EMPRESA empresa
JOIN SYN_ASESORIA asesoria
  ON empresa.IDEMPRESA = asesoria.IDEMPRESA 
WHERE asesoria.FIN < TRUNC(SYSDATE, 'YYYY')
GROUP BY
  empresa.RUT_EMPRESA,
  empresa.DV_EMPRESA,
  empresa.NOMEMPRESA,
  empresa.IVA_DECLARADO,
  empresa.FECHA_INICIACION_ACTIVIDADES  
  ORDER BY
    NOMBRE_EMPRESA;

-- CASO 3.2

-- ELIMINACIÓN INDEX
DROP INDEX IDX_ASESORIA_FIN_EMPRESA;


-- INDEX
CREATE INDEX IDX_ASESORIA_FIN_EMPRESA ON ASESORIA (IDEMPRESA, FIN);


-- USUARIO PRY2205_EFT_DES

SHOW USER;

-- CASO 2

-- OTORGAR PRIVILEGIOS A USUARIO CON     
GRANT SELECT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_ROL_C;  

-- CREACIÓN INSERT
INSERT INTO PRY2205_EFT.CARTOLA_PROFESIONALES
  SELECT
    p.RUTPROF                              AS RUT_PROFESIONAL,
    p.NOMPRO || ' ' || 
    p.APPPRO || ' ' || 
    p.APMPRO                               AS NOMBRE_PROFESIONAL,
    pr.NOMPROFESION                        AS PROFESION,
    i.NOMISAPRE                            AS ISAPRE,
    p.SUELDO                               AS SUELDO_BASE,
    NVL(p.COMISION, 0)                     AS PORC_COMISION_PROFESIONAL,
    NVL(p.SUELDO * p.COMISION, 0)          AS VALOR_TOTAL_COMISION,
    NVL(p.SUELDO * r.HONOR_PCT / 100, 0)   AS porcentaje_honorario,
    CASE tc.NOMTCONTRATO
        WHEN 'Indefinido Jornada Completa' THEN 150000
        WHEN 'Indefinido Jornada Parcial'  THEN 120000
        WHEN 'Plazo fijo'                  THEN 60000
        WHEN 'Honorarios'                  THEN 50000
        ELSE 0
    END                                    AS BONO_MOVILIZACION,
    p.SUELDO
    + NVL(p.SUELDO * p.COMISION, 0)
    + NVL(p.SUELDO * r.HONOR_PCT / 100, 0)
    + CASE tc.NOMTCONTRATO
        WHEN 'Indefinido Jornada Completa' THEN 150000
        WHEN 'Indefinido Jornada Parcial'  THEN 120000
        WHEN 'Plazo fijo'                  THEN 60000
        WHEN 'Honorarios'                  THEN 50000
        ELSE 0
      END                                  AS TOTAL_PAGAR
  FROM SYN_TRABAJADOR p
  JOIN SYN_PROF pr       ON p.IDPROFESION = pr.IDPROFESION
  JOIN SYN_PREVISON i           ON p.IDISAPRE = i.IDISAPRE
  JOIN SYN_CONT tc   ON p.IDTCONTRATO = tc.IDTCONTRATO
  LEFT JOIN SYN_PAGO r
       ON p.SUELDO BETWEEN r.S_MIN AND r.S_MAX;
COMMIT;     

-- USUARIO PRY2205_EFT_CON

SHOW USER;

-- CASO 2

SELECT * 
FROM PRY2205_EFT.CARTOLA_PROFESIONALES
ORDER BY
    PROFESION,
    SUELDO_BASE DESC,
    PORC_COMISION_PROFESIONAL,   
    RUT_PROFESIONAL;
    
-- CASO 3.1

SELECT * FROM PRY2205_EFT.VW_EMPRESAS_ASESORADAS;
